// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iynarfkdplimjrsvtgyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5bmFyZmtkcGxpbWpyc3Z0Z3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0MzA4NDcsImV4cCI6MjA1NDAwNjg0N30.GdbZeEO2UeWN6sqTtfhA-hdlbm1luRMz4hy0oD6yD3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);